baseURL = 'https://glittery-pastelito-c1831f.netlify.app/'
languageCode = 'en-us'
title = 'TravelKetoAI'
theme = 'custom'

[params]
featured_image = ""
hero_image = "images/heroimagesteak.jpg"
description = "Travel. Keto. Carnivore."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true