baseURL = 'https://travelketo.ai/'
languageCode = 'en-us'
title = 'TravelKetoAI'
theme = 'custom'

[pagination]
pagerSize = 10

[params]
featured_image = ""
hero_image = "images/heroimagesteak.jpg"
description = "Travel. Keto. Carnivore."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true