[build]
  command = "hugo --gc --minify --buildDrafts=false"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.115.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404